sudo: false
language: python
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
# If the SDK is not already cached, download it and unpack it
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash;
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
install:
- gcloud -q components update gae-python
script:
# Run unit tests here
- echo "No testing for now."
# Run E2E tests here
before_deploy:
  # authentication for dev project
  - provider: script
    script: scripts/auth.sh dev
    on:
      branch: bugfix/travis-ci-build
  # authentication for master project
  - provider: script
    script: scripts/auth.sh master
    on:
      branch: master
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: bugfix/travis-ci-build
  # deploy master to production
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master

