sudo: false
language: python
node_js:
  - "8"
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
# If the SDK is not already cached, download it and unpack it
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > output.txt;
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
install:
- gcloud -q components update gae-python
- pip install requests
script:
# Run unit tests here
- echo "Running unit tests now"
- cd app
- python tests.py
- cd ..
- echo "Finished unit tests and back in `pwd`"
# Run E2E tests here
deploy:
# Dev doesn't exist anymore for now
  # deploy develop to the staging environment
#  - provider: script
#    script: scripts/deploy.sh dev
#    on:
#      branch: dev
  # deploy master to production
  - provider: script
    script: scripts/deploy.sh master
    on:
      branch: master

